### ISSUE TITLE
horizbuttons-attention-m not working

### ISSUE THREAD

**Issue by blackgolfer** [TYPO3-Documentation/sphinx_typo3_theme#68] opened 2020-04-06 16:34 UTC
I am having trouble using horizbuttons-attention-m:

.. rst-class:: horizbuttons-note-m

- horizbuttons-note-m
- two
- three

The list is still vertical, and the buttons do not show up.

**Comment by marble** [comment] 2020-04-06 17:03
Probably some reST syntax error.

① Should be working, as can be seen here: https://docs.typo3.org/m/typo3/demo-t3SphinxThemeRtd/master/en-us/ListsAsButtons/Index.html#horizbuttons-note-m

② Please check YOURDOCS/_buildinfo/warnings.txt

③ If that doesn't help: Give us a link or copy and paste EXACTLY enough of your code!

**Comment by blackgolfer** [comment] 2020-04-07 03:14
Thanks very much for the reply, I was using sphinx-build to compile the sphinx project, that seems to be the problem. If sphinx-build is not the wrong build tool to use, I will upload my simple test to github for your checking. Thanks again.

**Comment by blackgolfer** [comment] 2020-04-07 06:38
I have created a simple testing project in github: https://github.com/blackgolfer/sphinx_typo3_theme_test.git

I also tested in the docs directory of this project and got the same problem.

Thanks for your time. This theme is really nice and I like the most among all themes I have tried. Great work !

**Comment by blackgolfer** [comment] 2020-04-07 06:51
Forgot to mention the info on testing env: Python 3.8.2, Sphinx 3.0 (also tested in 2.4.4), sphinx_typo3_theme 4.1.3

**Comment by marble** [comment] 2020-04-07 10:30
The actual theme work has been done by @benjaminkott . Great work, indeed! No other template dependencies!
Most probably the problem is that you are Python and Sphinx with up-to-date versions. Unfortunately we are using a Python toolchain which hasn't been rewritten for Python 3 yet. So we are stuck on Python 2.7 and Sphinx 1.8.x. But we are working on this. Until then I'm please to help you as it is of general interest to me/us as well.
Before I continue: 
(a) Which system are you on use (Mac, Linux, Win)? 
(b) Can you run Docker? 
(c) When I render your repo with our container [1] it looks perfect as expected.
(d) I'd started a Gist [2] just the other day showing how to set up a Python virtual environment for those of us who don't want the container but install things directly in a venv.

[1] https://github.com/t3docs/docker-render-documentation • https://docs.typo3.org/m/typo3/t3docs-docker-render-documentation/draft/en-us/
[2] https://gist.github.com/marble/b36c2988a56a28722b336b9be3f0127e

**Comment by blackgolfer** [comment] 2020-04-07 11:03
That is great at least I know it works in your environment. I am using linux, usually just use docker but for testing I have tested it with docker and without docker. I will upload my docker files and docker-compose file into the github testing project. Without the button list working, I will still use this theme, so I can wait for long time until it works in my environment, so no worry and no hurry. Thank you for your help, we will continue working on it......

**Comment by marble** [comment] 2020-04-07 13:31
I'll close the issue for now. I can reopen it whenever we need that. All the best!

**Closed by marble** 2020-04-07 13:31 UTC
